version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command:
      [
        "wait-for-it",
        "db:3306",
        "--timeout=60",
        "--strict",
        "--",
        "npm",
        "run",
        "start:dev",
      ]

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  seed:
    container_name: seed
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    entrypoint:
      [
        "wait-for-it",
        "db:3306",
        "--timeout=60",
        "--strict",
        "--",
        "npm",
        "run",
        "seed",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./backend:/app

volumes:
  db_data:
